### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement
  commentId: T:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement
  id: XmlDictionaryReaderQuotasElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  - CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  - CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  - CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  - CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  langs:
  - csharp
  - vb
  name: XmlDictionaryReaderQuotasElement
  nameWithType: XmlDictionaryReaderQuotasElement
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement
  type: Class
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: XmlDictionaryReaderQuotasElement
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 8
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public class XmlDictionaryReaderQuotasElement : ConfigurationElement'
    content.vb: >-
      Public Class XmlDictionaryReaderQuotasElement

          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  commentId: P:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  id: MaxDepth
  parent: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxDepth
  nameWithType: XmlDictionaryReaderQuotasElement.MaxDepth
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  type: Property
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: MaxDepth
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 11
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public int MaxDepth { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxDepth As Integer
  overload: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  commentId: P:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  id: MaxStringContentLength
  parent: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxStringContentLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxStringContentLength
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  type: Property
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: MaxStringContentLength
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 19
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public int MaxStringContentLength { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxStringContentLength As Integer
  overload: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  commentId: P:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  id: MaxArrayLength
  parent: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxArrayLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxArrayLength
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  type: Property
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: MaxArrayLength
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 27
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public int MaxArrayLength { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxArrayLength As Integer
  overload: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  commentId: P:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  id: MaxBytesPerRead
  parent: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxBytesPerRead
  nameWithType: XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  type: Property
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: MaxBytesPerRead
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 35
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public int MaxBytesPerRead { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxBytesPerRead As Integer
  overload: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  commentId: P:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  id: MaxNameTableCharCount
  parent: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxNameTableCharCount
  nameWithType: XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  type: Property
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: MaxNameTableCharCount
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 43
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public int MaxNameTableCharCount { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxNameTableCharCount As Integer
  overload: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth*
  commentId: Overload:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  name: MaxDepth
  nameWithType: XmlDictionaryReaderQuotasElement.MaxDepth
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength*
  commentId: Overload:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  name: MaxStringContentLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxStringContentLength
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength*
  commentId: Overload:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  name: MaxArrayLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxArrayLength
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead*
  commentId: Overload:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  name: MaxBytesPerRead
  nameWithType: XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
- uid: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount*
  commentId: Overload:CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  name: MaxNameTableCharCount
  nameWithType: XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  fullName: CoreWCF.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
