### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.IBindingFactory
  commentId: T:CoreWCF.Configuration.IBindingFactory
  id: IBindingFactory
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.IBindingFactory.Create(System.String)
  langs:
  - csharp
  - vb
  name: IBindingFactory
  nameWithType: IBindingFactory
  fullName: CoreWCF.Configuration.IBindingFactory
  type: Interface
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/IBindingFactory.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: IBindingFactory
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/IBindingFactory.cs
    startLine: 7
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public interface IBindingFactory
    content.vb: Public Interface IBindingFactory
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: CoreWCF.Configuration.IBindingFactory.Create(System.String)
  commentId: M:CoreWCF.Configuration.IBindingFactory.Create(System.String)
  id: Create(System.String)
  parent: CoreWCF.Configuration.IBindingFactory
  langs:
  - csharp
  - vb
  name: Create(String)
  nameWithType: IBindingFactory.Create(String)
  fullName: CoreWCF.Configuration.IBindingFactory.Create(System.String)
  type: Method
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/IBindingFactory.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: Create
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/IBindingFactory.cs
    startLine: 9
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: Binding Create(string bindingType)
    parameters:
    - id: bindingType
      type: System.String
    return:
      type: CoreWCF.Channels.Binding
    content.vb: Function Create(bindingType As String) As Binding
  overload: CoreWCF.Configuration.IBindingFactory.Create*
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: CoreWCF.Configuration.IBindingFactory.Create*
  commentId: Overload:CoreWCF.Configuration.IBindingFactory.Create
  name: Create
  nameWithType: IBindingFactory.Create
  fullName: CoreWCF.Configuration.IBindingFactory.Create
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.Channels.Binding
  commentId: T:CoreWCF.Channels.Binding
  parent: CoreWCF.Channels
  name: Binding
  nameWithType: Binding
  fullName: CoreWCF.Channels.Binding
- uid: CoreWCF.Channels
  commentId: N:CoreWCF.Channels
  name: CoreWCF.Channels
  nameWithType: CoreWCF.Channels
  fullName: CoreWCF.Channels
