### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.MapMiddleware
  commentId: T:CoreWCF.Configuration.MapMiddleware
  id: MapMiddleware
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.MapMiddleware.#ctor(CoreWCF.Configuration.HandshakeDelegate,CoreWCF.Configuration.MapOptions)
  - CoreWCF.Configuration.MapMiddleware.Invoke(CoreWCF.Channels.Framing.FramingConnection)
  langs:
  - csharp
  - vb
  name: MapMiddleware
  nameWithType: MapMiddleware
  fullName: CoreWCF.Configuration.MapMiddleware
  type: Class
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/Configuration/MapMiddleware.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: MapMiddleware
    path: src/CoreWCF.NetTcp/src/CoreWCF/Configuration/MapMiddleware.cs
    startLine: 12
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  summary: "\nRepresents a middleware that maps a request path to a sub-request pipeline.\n"
  example: []
  syntax:
    content: 'public class MapMiddleware : object'
    content.vb: >-
      Public Class MapMiddleware

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.MapMiddleware.#ctor(CoreWCF.Configuration.HandshakeDelegate,CoreWCF.Configuration.MapOptions)
  commentId: M:CoreWCF.Configuration.MapMiddleware.#ctor(CoreWCF.Configuration.HandshakeDelegate,CoreWCF.Configuration.MapOptions)
  id: '#ctor(CoreWCF.Configuration.HandshakeDelegate,CoreWCF.Configuration.MapOptions)'
  parent: CoreWCF.Configuration.MapMiddleware
  langs:
  - csharp
  - vb
  name: MapMiddleware(HandshakeDelegate, MapOptions)
  nameWithType: MapMiddleware.MapMiddleware(HandshakeDelegate, MapOptions)
  fullName: CoreWCF.Configuration.MapMiddleware.MapMiddleware(CoreWCF.Configuration.HandshakeDelegate, CoreWCF.Configuration.MapOptions)
  type: Constructor
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/Configuration/MapMiddleware.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: .ctor
    path: src/CoreWCF.NetTcp/src/CoreWCF/Configuration/MapMiddleware.cs
    startLine: 22
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  summary: "\nCreates a new instance of <xref href=\"CoreWCF.Configuration.MapMiddleware\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public MapMiddleware(HandshakeDelegate next, MapOptions options)
    parameters:
    - id: next
      type: CoreWCF.Configuration.HandshakeDelegate
      description: The delegate representing the next middleware in the request pipeline.
    - id: options
      type: CoreWCF.Configuration.MapOptions
      description: The middleware options.
    content.vb: Public Sub New(next As HandshakeDelegate, options As MapOptions)
  overload: CoreWCF.Configuration.MapMiddleware.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.MapMiddleware.Invoke(CoreWCF.Channels.Framing.FramingConnection)
  commentId: M:CoreWCF.Configuration.MapMiddleware.Invoke(CoreWCF.Channels.Framing.FramingConnection)
  id: Invoke(CoreWCF.Channels.Framing.FramingConnection)
  parent: CoreWCF.Configuration.MapMiddleware
  langs:
  - csharp
  - vb
  name: Invoke(FramingConnection)
  nameWithType: MapMiddleware.Invoke(FramingConnection)
  fullName: CoreWCF.Configuration.MapMiddleware.Invoke(CoreWCF.Channels.Framing.FramingConnection)
  type: Method
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/Configuration/MapMiddleware.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: Invoke
    path: src/CoreWCF.NetTcp/src/CoreWCF/Configuration/MapMiddleware.cs
    startLine: 33
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  summary: "\nExecutes the middleware.\n"
  example: []
  syntax:
    content: public async Task Invoke(FramingConnection connection)
    parameters:
    - id: connection
      type: CoreWCF.Channels.Framing.FramingConnection
    return:
      type: Task
      description: A task that represents the execution of this middleware.
    content.vb: Public Function Invoke(connection As FramingConnection) As Task
  overload: CoreWCF.Configuration.MapMiddleware.Invoke*
  modifiers.csharp:
  - public
  - async
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.MapMiddleware
  commentId: T:CoreWCF.Configuration.MapMiddleware
  name: MapMiddleware
  nameWithType: MapMiddleware
  fullName: CoreWCF.Configuration.MapMiddleware
- uid: CoreWCF.Configuration.MapMiddleware.#ctor*
  commentId: Overload:CoreWCF.Configuration.MapMiddleware.#ctor
  name: MapMiddleware
  nameWithType: MapMiddleware.MapMiddleware
  fullName: CoreWCF.Configuration.MapMiddleware.MapMiddleware
- uid: CoreWCF.Configuration.HandshakeDelegate
  commentId: T:CoreWCF.Configuration.HandshakeDelegate
  parent: CoreWCF.Configuration
  name: HandshakeDelegate
  nameWithType: HandshakeDelegate
  fullName: CoreWCF.Configuration.HandshakeDelegate
- uid: CoreWCF.Configuration.MapOptions
  commentId: T:CoreWCF.Configuration.MapOptions
  parent: CoreWCF.Configuration
  name: MapOptions
  nameWithType: MapOptions
  fullName: CoreWCF.Configuration.MapOptions
- uid: CoreWCF.Configuration.MapMiddleware.Invoke*
  commentId: Overload:CoreWCF.Configuration.MapMiddleware.Invoke
  name: Invoke
  nameWithType: MapMiddleware.Invoke
  fullName: CoreWCF.Configuration.MapMiddleware.Invoke
- uid: CoreWCF.Channels.Framing.FramingConnection
  commentId: T:CoreWCF.Channels.Framing.FramingConnection
  parent: CoreWCF.Channels.Framing
  name: FramingConnection
  nameWithType: FramingConnection
  fullName: CoreWCF.Channels.Framing.FramingConnection
- uid: Task
  isExternal: true
  name: Task
  nameWithType: Task
  fullName: Task
- uid: CoreWCF.Channels.Framing
  commentId: N:CoreWCF.Channels.Framing
  name: CoreWCF.Channels.Framing
  nameWithType: CoreWCF.Channels.Framing
  fullName: CoreWCF.Channels.Framing
