### YamlMime:ManagedReference
items:
- uid: CoreWCF.TcpTransportSecurity
  commentId: T:CoreWCF.TcpTransportSecurity
  id: TcpTransportSecurity
  parent: CoreWCF
  children:
  - CoreWCF.TcpTransportSecurity.#ctor
  - CoreWCF.TcpTransportSecurity.ClientCredentialType
  - CoreWCF.TcpTransportSecurity.ExtendedProtectionPolicy
  - CoreWCF.TcpTransportSecurity.ProtectionLevel
  - CoreWCF.TcpTransportSecurity.SslProtocols
  langs:
  - csharp
  - vb
  name: TcpTransportSecurity
  nameWithType: TcpTransportSecurity
  fullName: CoreWCF.TcpTransportSecurity
  type: Class
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: TcpTransportSecurity
    path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
    startLine: 13
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: 'public sealed class TcpTransportSecurity : object'
    content.vb: >-
      Public NotInheritable Class TcpTransportSecurity

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.TcpTransportSecurity.#ctor
  commentId: M:CoreWCF.TcpTransportSecurity.#ctor
  id: '#ctor'
  parent: CoreWCF.TcpTransportSecurity
  langs:
  - csharp
  - vb
  name: TcpTransportSecurity()
  nameWithType: TcpTransportSecurity.TcpTransportSecurity()
  fullName: CoreWCF.TcpTransportSecurity.TcpTransportSecurity()
  type: Constructor
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: .ctor
    path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
    startLine: 23
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: public TcpTransportSecurity()
    content.vb: Public Sub New
  overload: CoreWCF.TcpTransportSecurity.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.TcpTransportSecurity.ClientCredentialType
  commentId: P:CoreWCF.TcpTransportSecurity.ClientCredentialType
  id: ClientCredentialType
  parent: CoreWCF.TcpTransportSecurity
  langs:
  - csharp
  - vb
  name: ClientCredentialType
  nameWithType: TcpTransportSecurity.ClientCredentialType
  fullName: CoreWCF.TcpTransportSecurity.ClientCredentialType
  type: Property
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: ClientCredentialType
    path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
    startLine: 31
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: public TcpClientCredentialType ClientCredentialType { get; set; }
    parameters: []
    return:
      type: CoreWCF.TcpClientCredentialType
    content.vb: Public Property ClientCredentialType As TcpClientCredentialType
  overload: CoreWCF.TcpTransportSecurity.ClientCredentialType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.TcpTransportSecurity.ProtectionLevel
  commentId: P:CoreWCF.TcpTransportSecurity.ProtectionLevel
  id: ProtectionLevel
  parent: CoreWCF.TcpTransportSecurity
  langs:
  - csharp
  - vb
  name: ProtectionLevel
  nameWithType: TcpTransportSecurity.ProtectionLevel
  fullName: CoreWCF.TcpTransportSecurity.ProtectionLevel
  type: Property
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: ProtectionLevel
    path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
    startLine: 45
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: public ProtectionLevel ProtectionLevel { get; set; }
    parameters: []
    return:
      type: ProtectionLevel
    content.vb: Public Property ProtectionLevel As ProtectionLevel
  overload: CoreWCF.TcpTransportSecurity.ProtectionLevel*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.TcpTransportSecurity.ExtendedProtectionPolicy
  commentId: P:CoreWCF.TcpTransportSecurity.ExtendedProtectionPolicy
  id: ExtendedProtectionPolicy
  parent: CoreWCF.TcpTransportSecurity
  langs:
  - csharp
  - vb
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurity.ExtendedProtectionPolicy
  fullName: CoreWCF.TcpTransportSecurity.ExtendedProtectionPolicy
  type: Property
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: ExtendedProtectionPolicy
    path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
    startLine: 59
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: public ExtendedProtectionPolicy ExtendedProtectionPolicy { get; set; }
    parameters: []
    return:
      type: ExtendedProtectionPolicy
    content.vb: Public Property ExtendedProtectionPolicy As ExtendedProtectionPolicy
  overload: CoreWCF.TcpTransportSecurity.ExtendedProtectionPolicy*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.TcpTransportSecurity.SslProtocols
  commentId: P:CoreWCF.TcpTransportSecurity.SslProtocols
  id: SslProtocols
  parent: CoreWCF.TcpTransportSecurity
  langs:
  - csharp
  - vb
  name: SslProtocols
  nameWithType: TcpTransportSecurity.SslProtocols
  fullName: CoreWCF.TcpTransportSecurity.SslProtocols
  type: Property
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: SslProtocols
    path: src/CoreWCF.NetTcp/src/CoreWCF/TcpTransportSecurity.cs
    startLine: 82
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: public SslProtocols SslProtocols { get; set; }
    parameters: []
    return:
      type: SslProtocols
    content.vb: Public Property SslProtocols As SslProtocols
  overload: CoreWCF.TcpTransportSecurity.SslProtocols*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF
  commentId: N:CoreWCF
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.TcpTransportSecurity.#ctor*
  commentId: Overload:CoreWCF.TcpTransportSecurity.#ctor
  name: TcpTransportSecurity
  nameWithType: TcpTransportSecurity.TcpTransportSecurity
  fullName: CoreWCF.TcpTransportSecurity.TcpTransportSecurity
- uid: CoreWCF.TcpTransportSecurity.ClientCredentialType*
  commentId: Overload:CoreWCF.TcpTransportSecurity.ClientCredentialType
  name: ClientCredentialType
  nameWithType: TcpTransportSecurity.ClientCredentialType
  fullName: CoreWCF.TcpTransportSecurity.ClientCredentialType
- uid: CoreWCF.TcpClientCredentialType
  commentId: T:CoreWCF.TcpClientCredentialType
  parent: CoreWCF
  name: TcpClientCredentialType
  nameWithType: TcpClientCredentialType
  fullName: CoreWCF.TcpClientCredentialType
- uid: CoreWCF.TcpTransportSecurity.ProtectionLevel*
  commentId: Overload:CoreWCF.TcpTransportSecurity.ProtectionLevel
  name: ProtectionLevel
  nameWithType: TcpTransportSecurity.ProtectionLevel
  fullName: CoreWCF.TcpTransportSecurity.ProtectionLevel
- uid: ProtectionLevel
  commentId: '!:ProtectionLevel'
  isExternal: true
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: ProtectionLevel
- uid: CoreWCF.TcpTransportSecurity.ExtendedProtectionPolicy*
  commentId: Overload:CoreWCF.TcpTransportSecurity.ExtendedProtectionPolicy
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurity.ExtendedProtectionPolicy
  fullName: CoreWCF.TcpTransportSecurity.ExtendedProtectionPolicy
- uid: ExtendedProtectionPolicy
  isExternal: true
  name: ExtendedProtectionPolicy
  nameWithType: ExtendedProtectionPolicy
  fullName: ExtendedProtectionPolicy
- uid: CoreWCF.TcpTransportSecurity.SslProtocols*
  commentId: Overload:CoreWCF.TcpTransportSecurity.SslProtocols
  name: SslProtocols
  nameWithType: TcpTransportSecurity.SslProtocols
  fullName: CoreWCF.TcpTransportSecurity.SslProtocols
- uid: SslProtocols
  isExternal: true
  name: SslProtocols
  nameWithType: SslProtocols
  fullName: SslProtocols
