### YamlMime:ManagedReference
items:
- uid: CoreWCF.NetTcpSecurity
  commentId: T:CoreWCF.NetTcpSecurity
  id: NetTcpSecurity
  parent: CoreWCF
  children:
  - CoreWCF.NetTcpSecurity.#ctor
  - CoreWCF.NetTcpSecurity.Message
  - CoreWCF.NetTcpSecurity.Mode
  - CoreWCF.NetTcpSecurity.Transport
  langs:
  - csharp
  - vb
  name: NetTcpSecurity
  nameWithType: NetTcpSecurity
  fullName: CoreWCF.NetTcpSecurity
  type: Class
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: NetTcpSecurity
    path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
    startLine: 11
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: 'public sealed class NetTcpSecurity : object'
    content.vb: >-
      Public NotInheritable Class NetTcpSecurity

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.NetTcpSecurity.#ctor
  commentId: M:CoreWCF.NetTcpSecurity.#ctor
  id: '#ctor'
  parent: CoreWCF.NetTcpSecurity
  langs:
  - csharp
  - vb
  name: NetTcpSecurity()
  nameWithType: NetTcpSecurity.NetTcpSecurity()
  fullName: CoreWCF.NetTcpSecurity.NetTcpSecurity()
  type: Constructor
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: .ctor
    path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
    startLine: 16
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: public NetTcpSecurity()
    content.vb: Public Sub New
  overload: CoreWCF.NetTcpSecurity.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.NetTcpSecurity.Mode
  commentId: P:CoreWCF.NetTcpSecurity.Mode
  id: Mode
  parent: CoreWCF.NetTcpSecurity
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: NetTcpSecurity.Mode
  fullName: CoreWCF.NetTcpSecurity.Mode
  type: Property
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: Mode
    path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
    startLine: 30
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: public SecurityMode Mode { get; set; }
    parameters: []
    return:
      type: CoreWCF.SecurityMode
    content.vb: Public Property Mode As SecurityMode
  overload: CoreWCF.NetTcpSecurity.Mode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.NetTcpSecurity.Transport
  commentId: P:CoreWCF.NetTcpSecurity.Transport
  id: Transport
  parent: CoreWCF.NetTcpSecurity
  langs:
  - csharp
  - vb
  name: Transport
  nameWithType: NetTcpSecurity.Transport
  fullName: CoreWCF.NetTcpSecurity.Transport
  type: Property
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: Transport
    path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
    startLine: 44
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: public TcpTransportSecurity Transport { get; set; }
    parameters: []
    return:
      type: CoreWCF.TcpTransportSecurity
    content.vb: Public Property Transport As TcpTransportSecurity
  overload: CoreWCF.NetTcpSecurity.Transport*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.NetTcpSecurity.Message
  commentId: P:CoreWCF.NetTcpSecurity.Message
  id: Message
  parent: CoreWCF.NetTcpSecurity
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: NetTcpSecurity.Message
  fullName: CoreWCF.NetTcpSecurity.Message
  type: Property
  source:
    remote:
      path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: Message
    path: src/CoreWCF.NetTcp/src/CoreWCF/NetTcpSecurity.cs
    startLine: 46
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF
  syntax:
    content: public MessageSecurityOverTcp Message { get; set; }
    parameters: []
    return:
      type: CoreWCF.Security.MessageSecurityOverTcp
    content.vb: Public Property Message As MessageSecurityOverTcp
  overload: CoreWCF.NetTcpSecurity.Message*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF
  commentId: N:CoreWCF
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.NetTcpSecurity.#ctor*
  commentId: Overload:CoreWCF.NetTcpSecurity.#ctor
  name: NetTcpSecurity
  nameWithType: NetTcpSecurity.NetTcpSecurity
  fullName: CoreWCF.NetTcpSecurity.NetTcpSecurity
- uid: CoreWCF.NetTcpSecurity.Mode*
  commentId: Overload:CoreWCF.NetTcpSecurity.Mode
  name: Mode
  nameWithType: NetTcpSecurity.Mode
  fullName: CoreWCF.NetTcpSecurity.Mode
- uid: CoreWCF.SecurityMode
  commentId: T:CoreWCF.SecurityMode
  parent: CoreWCF
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: CoreWCF.SecurityMode
- uid: CoreWCF.NetTcpSecurity.Transport*
  commentId: Overload:CoreWCF.NetTcpSecurity.Transport
  name: Transport
  nameWithType: NetTcpSecurity.Transport
  fullName: CoreWCF.NetTcpSecurity.Transport
- uid: CoreWCF.TcpTransportSecurity
  commentId: T:CoreWCF.TcpTransportSecurity
  parent: CoreWCF
  name: TcpTransportSecurity
  nameWithType: TcpTransportSecurity
  fullName: CoreWCF.TcpTransportSecurity
- uid: CoreWCF.NetTcpSecurity.Message*
  commentId: Overload:CoreWCF.NetTcpSecurity.Message
  name: Message
  nameWithType: NetTcpSecurity.Message
  fullName: CoreWCF.NetTcpSecurity.Message
- uid: CoreWCF.Security.MessageSecurityOverTcp
  commentId: T:CoreWCF.Security.MessageSecurityOverTcp
  parent: CoreWCF.Security
  name: MessageSecurityOverTcp
  nameWithType: MessageSecurityOverTcp
  fullName: CoreWCF.Security.MessageSecurityOverTcp
- uid: CoreWCF.Security
  commentId: N:CoreWCF.Security
  name: CoreWCF.Security
  nameWithType: CoreWCF.Security
  fullName: CoreWCF.Security
