### YamlMime:ManagedReference
items:
- uid: CoreWCF.HttpTransportSecurity
  commentId: T:CoreWCF.HttpTransportSecurity
  id: HttpTransportSecurity
  parent: CoreWCF
  children:
  - CoreWCF.HttpTransportSecurity.#ctor
  - CoreWCF.HttpTransportSecurity.ClientCredentialType
  - CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  - CoreWCF.HttpTransportSecurity.Realm
  langs:
  - csharp
  - vb
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: CoreWCF.HttpTransportSecurity
  type: Class
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: HttpTransportSecurity
    path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
    startLine: 10
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: 'public sealed class HttpTransportSecurity : object'
    content.vb: >-
      Public NotInheritable Class HttpTransportSecurity

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.HttpTransportSecurity.#ctor
  commentId: M:CoreWCF.HttpTransportSecurity.#ctor
  id: '#ctor'
  parent: CoreWCF.HttpTransportSecurity
  langs:
  - csharp
  - vb
  name: HttpTransportSecurity()
  nameWithType: HttpTransportSecurity.HttpTransportSecurity()
  fullName: CoreWCF.HttpTransportSecurity.HttpTransportSecurity()
  type: Constructor
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: .ctor
    path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
    startLine: 17
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public HttpTransportSecurity()
    content.vb: Public Sub New
  overload: CoreWCF.HttpTransportSecurity.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.HttpTransportSecurity.ClientCredentialType
  commentId: P:CoreWCF.HttpTransportSecurity.ClientCredentialType
  id: ClientCredentialType
  parent: CoreWCF.HttpTransportSecurity
  langs:
  - csharp
  - vb
  name: ClientCredentialType
  nameWithType: HttpTransportSecurity.ClientCredentialType
  fullName: CoreWCF.HttpTransportSecurity.ClientCredentialType
  type: Property
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: ClientCredentialType
    path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
    startLine: 24
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public HttpClientCredentialType ClientCredentialType { get; set; }
    parameters: []
    return:
      type: CoreWCF.HttpClientCredentialType
    content.vb: Public Property ClientCredentialType As HttpClientCredentialType
  overload: CoreWCF.HttpTransportSecurity.ClientCredentialType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.HttpTransportSecurity.Realm
  commentId: P:CoreWCF.HttpTransportSecurity.Realm
  id: Realm
  parent: CoreWCF.HttpTransportSecurity
  langs:
  - csharp
  - vb
  name: Realm
  nameWithType: HttpTransportSecurity.Realm
  fullName: CoreWCF.HttpTransportSecurity.Realm
  type: Property
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: Realm
    path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
    startLine: 37
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public string Realm { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Realm As String
  overload: CoreWCF.HttpTransportSecurity.Realm*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  commentId: P:CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  id: ExtendedProtectionPolicy
  parent: CoreWCF.HttpTransportSecurity
  langs:
  - csharp
  - vb
  name: ExtendedProtectionPolicy
  nameWithType: HttpTransportSecurity.ExtendedProtectionPolicy
  fullName: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  type: Property
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: ExtendedProtectionPolicy
    path: src/CoreWCF.Http/src/CoreWCF/HttpTransportSecurity.cs
    startLine: 39
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public ExtendedProtectionPolicy ExtendedProtectionPolicy { get; set; }
    parameters: []
    return:
      type: ExtendedProtectionPolicy
    content.vb: Public Property ExtendedProtectionPolicy As ExtendedProtectionPolicy
  overload: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF
  commentId: N:CoreWCF
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.HttpTransportSecurity.#ctor*
  commentId: Overload:CoreWCF.HttpTransportSecurity.#ctor
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity.HttpTransportSecurity
  fullName: CoreWCF.HttpTransportSecurity.HttpTransportSecurity
- uid: CoreWCF.HttpTransportSecurity.ClientCredentialType*
  commentId: Overload:CoreWCF.HttpTransportSecurity.ClientCredentialType
  name: ClientCredentialType
  nameWithType: HttpTransportSecurity.ClientCredentialType
  fullName: CoreWCF.HttpTransportSecurity.ClientCredentialType
- uid: CoreWCF.HttpClientCredentialType
  commentId: T:CoreWCF.HttpClientCredentialType
  parent: CoreWCF
  name: HttpClientCredentialType
  nameWithType: HttpClientCredentialType
  fullName: CoreWCF.HttpClientCredentialType
- uid: CoreWCF.HttpTransportSecurity.Realm*
  commentId: Overload:CoreWCF.HttpTransportSecurity.Realm
  name: Realm
  nameWithType: HttpTransportSecurity.Realm
  fullName: CoreWCF.HttpTransportSecurity.Realm
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy*
  commentId: Overload:CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  name: ExtendedProtectionPolicy
  nameWithType: HttpTransportSecurity.ExtendedProtectionPolicy
  fullName: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
- uid: ExtendedProtectionPolicy
  isExternal: true
  name: ExtendedProtectionPolicy
  nameWithType: ExtendedProtectionPolicy
  fullName: ExtendedProtectionPolicy
