### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ConfigurationManagerExtensions
  commentId: T:CoreWCF.Configuration.ConfigurationManagerExtensions
  id: ConfigurationManagerExtensions
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(IServiceCollection,System.String)
  langs:
  - csharp
  - vb
  name: ConfigurationManagerExtensions
  nameWithType: ConfigurationManagerExtensions
  fullName: CoreWCF.Configuration.ConfigurationManagerExtensions
  type: Class
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/ConfigurationManagerExtensions.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: ConfigurationManagerExtensions
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/ConfigurationManagerExtensions.cs
    startLine: 9
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public static class ConfigurationManagerExtensions : object'
    content.vb: >-
      Public Module ConfigurationManagerExtensions

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(IServiceCollection,System.String)
  commentId: M:CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(IServiceCollection,System.String)
  id: AddServiceModelConfigurationManagerFile(IServiceCollection,System.String)
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ConfigurationManagerExtensions
  langs:
  - csharp
  - vb
  name: AddServiceModelConfigurationManagerFile(IServiceCollection, String)
  nameWithType: ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(IServiceCollection, String)
  fullName: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(IServiceCollection, System.String)
  type: Method
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/ConfigurationManagerExtensions.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: AddServiceModelConfigurationManagerFile
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/ConfigurationManagerExtensions.cs
    startLine: 11
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IServiceCollection AddServiceModelConfigurationManagerFile(this IServiceCollection builder, string path)
    parameters:
    - id: builder
      type: IServiceCollection
    - id: path
      type: System.String
    return:
      type: IServiceCollection
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function AddServiceModelConfigurationManagerFile(builder As IServiceCollection, path As String) As IServiceCollection
  overload: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile*
  commentId: Overload:CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile
  name: AddServiceModelConfigurationManagerFile
  nameWithType: ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile
  fullName: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile
- uid: IServiceCollection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: IServiceCollection
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
