### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.BasicHttpBindingCollectionElement
  commentId: T:CoreWCF.Configuration.BasicHttpBindingCollectionElement
  id: BasicHttpBindingCollectionElement
  parent: CoreWCF.Configuration
  children: []
  langs:
  - csharp
  - vb
  name: BasicHttpBindingCollectionElement
  nameWithType: BasicHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.BasicHttpBindingCollectionElement
  type: Class
  source:
    remote:
      path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/BasicHttpBindingCollectionElement.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: BasicHttpBindingCollectionElement
    path: src/CoreWCF.ConfigurationManager/src/CoreWCF/Configuration/BasicHttpBindingCollectionElement.cs
    startLine: 5
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public class BasicHttpBindingCollectionElement : StandardBindingCollectionElement<BasicHttpBinding, BasicHttpBindingElement>'
    content.vb: >-
      Public Class BasicHttpBindingCollectionElement

          Inherits StandardBindingCollectionElement(Of BasicHttpBinding, BasicHttpBindingElement)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.BindingCollectionElement
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}
  inheritedMembers:
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}.Bindings
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.BindingCollectionElement
  commentId: T:CoreWCF.Configuration.BindingCollectionElement
  parent: CoreWCF.Configuration
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: CoreWCF.Configuration.BindingCollectionElement
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<BasicHttpBinding, BasicHttpBindingElement>
  nameWithType: StandardBindingCollectionElement<BasicHttpBinding, BasicHttpBindingElement>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.BasicHttpBinding, CoreWCF.Configuration.BasicHttpBindingElement>
  nameWithType.vb: StandardBindingCollectionElement(Of BasicHttpBinding, BasicHttpBindingElement)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.BasicHttpBinding, CoreWCF.Configuration.BasicHttpBindingElement)
  name.vb: StandardBindingCollectionElement(Of BasicHttpBinding, BasicHttpBindingElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.BasicHttpBinding
    name: BasicHttpBinding
    nameWithType: BasicHttpBinding
    fullName: CoreWCF.BasicHttpBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.BasicHttpBindingElement
    name: BasicHttpBindingElement
    nameWithType: BasicHttpBindingElement
    fullName: CoreWCF.Configuration.BasicHttpBindingElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.BasicHttpBinding
    name: BasicHttpBinding
    nameWithType: BasicHttpBinding
    fullName: CoreWCF.BasicHttpBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.BasicHttpBindingElement
    name: BasicHttpBindingElement
    nameWithType: BasicHttpBindingElement
    fullName: CoreWCF.Configuration.BasicHttpBindingElement
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}.Bindings
  parent: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  name: Bindings
  nameWithType: StandardBindingCollectionElement<BasicHttpBinding, BasicHttpBindingElement>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.BasicHttpBinding, CoreWCF.Configuration.BasicHttpBindingElement>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of BasicHttpBinding, BasicHttpBindingElement).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.BasicHttpBinding, CoreWCF.Configuration.BasicHttpBindingElement).Bindings
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  name.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  name: Bindings
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
