### YamlMime:ManagedReference
items:
- uid: CoreWCF.WSHTTPSecurity
  commentId: T:CoreWCF.WSHTTPSecurity
  id: WSHTTPSecurity
  parent: CoreWCF
  children:
  - CoreWCF.WSHTTPSecurity.#ctor
  - CoreWCF.WSHTTPSecurity.Message
  - CoreWCF.WSHTTPSecurity.Mode
  - CoreWCF.WSHTTPSecurity.ShouldSerializeMode
  - CoreWCF.WSHTTPSecurity.Transport
  langs:
  - csharp
  - vb
  name: WSHTTPSecurity
  nameWithType: WSHTTPSecurity
  fullName: CoreWCF.WSHTTPSecurity
  type: Class
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: WSHTTPSecurity
    path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
    startLine: 9
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: 'public sealed class WSHTTPSecurity : object'
    content.vb: >-
      Public NotInheritable Class WSHTTPSecurity

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.WSHTTPSecurity.#ctor
  commentId: M:CoreWCF.WSHTTPSecurity.#ctor
  id: '#ctor'
  parent: CoreWCF.WSHTTPSecurity
  langs:
  - csharp
  - vb
  name: WSHTTPSecurity()
  nameWithType: WSHTTPSecurity.WSHTTPSecurity()
  fullName: CoreWCF.WSHTTPSecurity.WSHTTPSecurity()
  type: Constructor
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: .ctor
    path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
    startLine: 16
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public WSHTTPSecurity()
    content.vb: Public Sub New
  overload: CoreWCF.WSHTTPSecurity.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.WSHTTPSecurity.Mode
  commentId: P:CoreWCF.WSHTTPSecurity.Mode
  id: Mode
  parent: CoreWCF.WSHTTPSecurity
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: WSHTTPSecurity.Mode
  fullName: CoreWCF.WSHTTPSecurity.Mode
  type: Property
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: Mode
    path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
    startLine: 37
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public SecurityMode Mode { get; set; }
    parameters: []
    return:
      type: CoreWCF.SecurityMode
    content.vb: Public Property Mode As SecurityMode
  overload: CoreWCF.WSHTTPSecurity.Mode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.WSHTTPSecurity.Transport
  commentId: P:CoreWCF.WSHTTPSecurity.Transport
  id: Transport
  parent: CoreWCF.WSHTTPSecurity
  langs:
  - csharp
  - vb
  name: Transport
  nameWithType: WSHTTPSecurity.Transport
  fullName: CoreWCF.WSHTTPSecurity.Transport
  type: Property
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: Transport
    path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
    startLine: 50
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public HttpTransportSecurity Transport { get; set; }
    parameters: []
    return:
      type: CoreWCF.HttpTransportSecurity
    content.vb: Public Property Transport As HttpTransportSecurity
  overload: CoreWCF.WSHTTPSecurity.Transport*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.WSHTTPSecurity.Message
  commentId: P:CoreWCF.WSHTTPSecurity.Message
  id: Message
  parent: CoreWCF.WSHTTPSecurity
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: WSHTTPSecurity.Message
  fullName: CoreWCF.WSHTTPSecurity.Message
  type: Property
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: Message
    path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
    startLine: 59
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public NonDualMessageSecurityOverHttp Message { get; set; }
    parameters: []
    return:
      type: CoreWCF.NonDualMessageSecurityOverHttp
    content.vb: Public Property Message As NonDualMessageSecurityOverHttp
  overload: CoreWCF.WSHTTPSecurity.Message*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.WSHTTPSecurity.ShouldSerializeMode
  commentId: M:CoreWCF.WSHTTPSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: CoreWCF.WSHTTPSecurity
  langs:
  - csharp
  - vb
  name: ShouldSerializeMode()
  nameWithType: WSHTTPSecurity.ShouldSerializeMode()
  fullName: CoreWCF.WSHTTPSecurity.ShouldSerializeMode()
  type: Method
  source:
    remote:
      path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
      branch: main
      repo: https://github.com/samsp-msft/CoreWCF.git
    id: ShouldSerializeMode
    path: src/CoreWCF.Http/src/CoreWCF/WSHTTPSecurity.cs
    startLine: 122
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public bool ShouldSerializeMode()
    return:
      type: System.Boolean
    content.vb: Public Function ShouldSerializeMode As Boolean
  overload: CoreWCF.WSHTTPSecurity.ShouldSerializeMode*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF
  commentId: N:CoreWCF
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.WSHTTPSecurity.#ctor*
  commentId: Overload:CoreWCF.WSHTTPSecurity.#ctor
  name: WSHTTPSecurity
  nameWithType: WSHTTPSecurity.WSHTTPSecurity
  fullName: CoreWCF.WSHTTPSecurity.WSHTTPSecurity
- uid: CoreWCF.WSHTTPSecurity.Mode*
  commentId: Overload:CoreWCF.WSHTTPSecurity.Mode
  name: Mode
  nameWithType: WSHTTPSecurity.Mode
  fullName: CoreWCF.WSHTTPSecurity.Mode
- uid: CoreWCF.SecurityMode
  commentId: T:CoreWCF.SecurityMode
  parent: CoreWCF
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: CoreWCF.SecurityMode
- uid: CoreWCF.WSHTTPSecurity.Transport*
  commentId: Overload:CoreWCF.WSHTTPSecurity.Transport
  name: Transport
  nameWithType: WSHTTPSecurity.Transport
  fullName: CoreWCF.WSHTTPSecurity.Transport
- uid: CoreWCF.HttpTransportSecurity
  commentId: T:CoreWCF.HttpTransportSecurity
  parent: CoreWCF
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: CoreWCF.HttpTransportSecurity
- uid: CoreWCF.WSHTTPSecurity.Message*
  commentId: Overload:CoreWCF.WSHTTPSecurity.Message
  name: Message
  nameWithType: WSHTTPSecurity.Message
  fullName: CoreWCF.WSHTTPSecurity.Message
- uid: CoreWCF.NonDualMessageSecurityOverHttp
  commentId: T:CoreWCF.NonDualMessageSecurityOverHttp
  parent: CoreWCF
  name: NonDualMessageSecurityOverHttp
  nameWithType: NonDualMessageSecurityOverHttp
  fullName: CoreWCF.NonDualMessageSecurityOverHttp
- uid: CoreWCF.WSHTTPSecurity.ShouldSerializeMode*
  commentId: Overload:CoreWCF.WSHTTPSecurity.ShouldSerializeMode
  name: ShouldSerializeMode
  nameWithType: WSHTTPSecurity.ShouldSerializeMode
  fullName: CoreWCF.WSHTTPSecurity.ShouldSerializeMode
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
